from .heath_router import health_router
from .student_router import student_router
from .department_router import department_router
from .teacher_router import teacher_router
from .administrator_router import administrator_router
from .lecture_router import lecture_router
from .warning_router import warning_router
from .schedule_router import schedule_router
from .take_router import take_router