from .student_queries import StudentQueries
from .department_queries import DepartmentQueries
from .teacher_queries import TeacherQueries
from .administrator_queries import AdministratorQueries
from .lecture_queries import LectureQueries
from .warning_queries import WarningQueries
from .schedule_queries import ScheduleQueries
from .take_queries import TakeQueries
from .teach_queries import TeachQueries